[CI] cleanup commit-stage workflow.

diff --git a/.github/workflows/commit-stage.yml b/.github/workflows/commit-stage.yml
--- a/.github/workflows/commit-stage.yml
+++ b/.github/workflows/commit-stage.yml
@@ -18,10 +18,12 @@ jobs:
         steps:
             - name: Checkout
               uses: actions/checkout@v2
+
             - name: QA - Run composer validate
               uses: docker://jakzal/phpqa:php7.4-alpine
               with:
                   args: composer validate --strict --ansi
+
             - name: QA - Run composer normalize
               uses: docker://jakzal/phpqa:php7.4-alpine
               with:
@@ -29,7 +31,6 @@ jobs:
 
 
     php-cs-fixer:
-        #if: ${{ github.event.workflow_run.conclusion == 'Success' }}
         name: Code style check
         runs-on: ubuntu-latest
         timeout-minutes: 20
@@ -40,49 +41,48 @@ jobs:
             fail-fast: true
 
         steps:
-            -
-                name: Checkout
-                uses: actions/checkout@v2
-            -
-                name: Setup php extension cache environment
-                id: cache-php-extensions
-                uses: shivammathur/cache-extensions@v1
-                with:
-                    php-version: ${{ matrix.php }}
-                    extensions: ${{ env.PHP_EXTENSIONS }}
-                    key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}
-            -
-                name: Cache PHP extensions
-                uses: actions/cache@v2
-                with:
-                    path: ${{ steps.cache-php-extensions.outputs.dir }}
-                    key: ${{ steps.cache-php-extensions.outputs.key }}
-                    restore-keys: ${{ steps.cache-php-extensions.outputs.key }}
-            -
-                name: Setup PHP
-                uses: shivammathur/setup-php@v2
-                with:
-                    php-version: ${{ matrix.php }}
-                    extensions: ${{ env.PHP_EXTENSIONS }}
-                    ini-values: memory_limit=-1
-                    coverage: none
-            -
-                name: Get Composer Cache Directory
-                id: composer-cache
-                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
-            -
-                name: Cache dependencies
-                uses: actions/cache@v2
-                with:
-                    path: ${{ steps.composer-cache.outputs.dir }}
-                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
-                    restore-keys: ${{ runner.os }}-composer-
-            -
-                name: Install Composer dependencies
-                run: composer install --prefer-dist --no-progress --no-suggest --ansi --no-scripts
-            -
-                name: Run PHP-CS-Fixer fix
-                run: vendor/bin/php-cs-fixer fix --dry-run --diff --ansi
+            - name: Checkout
+              uses: actions/checkout@v2
+
+            - name: Setup php extension cache environment
+              id: cache-php-extensions
+              uses: shivammathur/cache-extensions@v1
+              with:
+                php-version: ${{ matrix.php }}
+                extensions: ${{ env.PHP_EXTENSIONS }}
+                key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}
+
+            - name: Cache PHP extensions
+              uses: actions/cache@v2
+              with:
+                path: ${{ steps.cache-php-extensions.outputs.dir }}
+                key: ${{ steps.cache-php-extensions.outputs.key }}
+                restore-keys: ${{ steps.cache-php-extensions.outputs.key }}
+
+            - name: Setup PHP
+              uses: shivammathur/setup-php@v2
+              with:
+                php-version: ${{ matrix.php }}
+                extensions: ${{ env.PHP_EXTENSIONS }}
+                ini-values: memory_limit=-1
+                coverage: none
+
+            - name: Get Composer Cache Directory
+              id: composer-cache
+              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+
+            - name: Cache dependencies
+              uses: actions/cache@v2
+              with:
+                path: ${{ steps.composer-cache.outputs.dir }}
+                key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
+                restore-keys: ${{ runner.os }}-composer-
+
+            - name: Install Composer dependencies
+              run: composer install --prefer-dist --no-progress --no-suggest --ansi --no-scripts
+
+            - name: Run PHP-CS-Fixer fix
+              run: vendor/bin/php-cs-fixer fix --dry-run --diff --ansi
 
 
     php-stan:
@@ -96,49 +96,48 @@ jobs:
             fail-fast: true
 
         steps:
-            -
-                name: Checkout
-                uses: actions/checkout@v2
-            -
-                name: Setup php extension cache environment
-                id: cache-php-extensions
-                uses: shivammathur/cache-extensions@v1
-                with:
-                    php-version: ${{ matrix.php }}
-                    extensions: ${{ env.PHP_EXTENSIONS }}
-                    key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}
-            -
-                name: Cache PHP extensions
-                uses: actions/cache@v2
-                with:
-                    path: ${{ steps.cache-php-extensions.outputs.dir }}
-                    key: ${{ steps.cache-php-extensions.outputs.key }}
-                    restore-keys: ${{ steps.cache-php-extensions.outputs.key }}
-            -
-                name: Setup PHP
-                uses: shivammathur/setup-php@v2
-                with:
-                    php-version: ${{ matrix.php }}
-                    extensions: ${{ env.PHP_EXTENSIONS }}
-                    ini-values: memory_limit=-1
-                    coverage: none
-            -
-                name: Get Composer Cache Directory
-                id: composer-cache
-                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
-            -
-                name: Cache dependencies
-                uses: actions/cache@v2
-                with:
-                    path: ${{ steps.composer-cache.outputs.dir }}
-                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
-                    restore-keys: ${{ runner.os }}-composer-
-            -
-                name: Install Composer dependencies
-                run: composer install --prefer-dist --no-progress --no-suggest --ansi --no-scripts
-            -
-                name: Run PHP-CS-Fixer fix
-                run: vendor/bin/phpstan analyse --ansi
+            - name: Checkout
+              uses: actions/checkout@v2
+
+            - name: Setup php extension cache environment
+              id: cache-php-extensions
+              uses: shivammathur/cache-extensions@v1
+              with:
+                  php-version: ${{ matrix.php }}
+                  extensions: ${{ env.PHP_EXTENSIONS }}
+                  key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}
+
+            - name: Cache PHP extensions
+              uses: actions/cache@v2
+              with:
+                  path: ${{ steps.cache-php-extensions.outputs.dir }}
+                  key: ${{ steps.cache-php-extensions.outputs.key }}
+                  restore-keys: ${{ steps.cache-php-extensions.outputs.key }}
+
+            - name: Setup PHP
+              uses: shivammathur/setup-php@v2
+              with:
+                  php-version: ${{ matrix.php }}
+                  extensions: ${{ env.PHP_EXTENSIONS }}
+                  ini-values: memory_limit=-1
+                  coverage: none
+
+            - name: Get Composer Cache Directory
+              id: composer-cache
+              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+
+            - name: Cache dependencies
+              uses: actions/cache@v2
+              with:
+                  path: ${{ steps.composer-cache.outputs.dir }}
+                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
+                  restore-keys: ${{ runner.os }}-composer-
+
+            - name: Install Composer dependencies
+              run: composer install --prefer-dist --no-progress --no-suggest --ansi --no-scripts
+
+            - name: Run PHP-CS-Fixer fix
+              run: vendor/bin/phpstan analyse --ansi
 
 
     phpunit:
@@ -166,125 +165,99 @@ jobs:
             fail-fast: true
 
         steps:
-            -
-                name: Checkout
-                uses: actions/checkout@v2
-            -
-                name: Setup php extension cache environment
-                id: cache-php-extensions
-                uses: shivammathur/cache-extensions@v1
-                with:
-                    php-version: ${{ matrix.php }}
-                    extensions: ${{ env.PHP_EXTENSIONS }}
-                    key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}
-            -
-                name: Cache PHP extensions
-                uses: actions/cache@v2
-                with:
-                    path: ${{ steps.cache-php-extensions.outputs.dir }}
-                    key: ${{ steps.cache-php-extensions.outputs.key }}
-                    restore-keys: ${{ steps.cache-php-extensions.outputs.key }}
+            - name: Checkout
+              uses: actions/checkout@v2
 
-            -
-                name: setup-php
-                id: setup-php
-                uses: shivammathur/setup-php@v2
-                with:
-                    php-version: ${{ matrix.php }}
-                    extensions: ${{ env.PHP_EXTENSIONS }}
-                    ini-values: date.timezone=Europe/Rome, memory_limit=-1
-                    coverage: xdebug
-                    tools: symfony
+            - name: Setup php extension cache environment
+              id: cache-php-extensions
+              uses: shivammathur/cache-extensions@v1
+              with:
+                  php-version: ${{ matrix.php }}
+                  extensions: ${{ env.PHP_EXTENSIONS }}
+                  key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}
 
-            -
-                name: Reveal env vars
-                run: |
-                    echo GITHUB_WORKFLOW   = $GITHUB_WORKFLOW
-                    echo HOME              = $HOME
-                    echo GITHUB_ACTION     = $GITHUB_ACTION
-                    echo GITHUB_ACTIONS    = $GITHUB_ACTIONS
-                    echo GITHUB_ACTOR      = $GITHUB_ACTOR
-                    echo GITHUB_REPOSITORY = $GITHUB_REPOSITORY
-                    echo GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME
-                    echo GITHUB_EVENT_PATH = $GITHUB_EVENT_PATH
-                    echo GITHUB_WORKSPACE  = $GITHUB_WORKSPACE
-                    echo GITHUB_SHA        = $GITHUB_SHA
-                    echo GITHUB_REF        = $GITHUB_REF
+            - name: Cache PHP extensions
+              uses: actions/cache@v2
+              with:
+                  path: ${{ steps.cache-php-extensions.outputs.dir }}
+                  key: ${{ steps.cache-php-extensions.outputs.key }}
+                  restore-keys: ${{ steps.cache-php-extensions.outputs.key }}
 
-            -
-                name: Get Composer Cache Directory
-                id: composer-cache
-                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+            - name: Setup PHP
+              uses: shivammathur/setup-php@v2
+              with:
+                  php-version: ${{ matrix.php }}
+                  extensions: ${{ env.PHP_EXTENSIONS }}
+                  ini-values: date.timezone=Europe/Rome, memory_limit=-1
+                  coverage: xdebug
+                  tools: symfony
 
-            -
-                name: Cache dependencies
-                uses: actions/cache@v2
-                with:
-                    path: ${{ steps.composer-cache.outputs.dir }}
-                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
-                    restore-keys: ${{ runner.os }}-composer-
+            - name: Get Composer Cache Directory
+              id: composer-cache
+              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
 
-            -
-                name: Install Composer dependencies
-                run: composer install --prefer-dist --no-progress --no-suggest --ansi --no-scripts
-            # -
-            #   name: Run Migration
-            #   run: |
-            #     php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
-            #     php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
-            #   env:
-            #     DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
+            - name: Cache dependencies
+              uses: actions/cache@v2
+              with:
+                  path: ${{ steps.composer-cache.outputs.dir }}
+                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
+                  restore-keys: ${{ runner.os }}-composer-
 
-            -
-                name: Enable code coverage
-                if: matrix.coverage
-                run: echo "COVERAGE=1" >> $GITHUB_ENV
+            - name: Install Composer dependencies
+              run: composer install --prefer-dist --no-progress --no-suggest --ansi --no-scripts
 
-            -
-                name: Install PHPUnit
-                run: bin/phpunit install
+#            - name: Run Migration
+#              run: |
+#                php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+#                php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+#              env:
+#                DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
 
-            -
-                name: Run Unit tests
-                #if: ${{ matrix.php == '7.2' }}
-                run: |
-                    mkdir -p reports/phpunit
-                    if [ "$COVERAGE" = '1' ]; then
-                      bin/phpunit --testsuite unit --coverage-clover reports/phpunit/unit-test-clover.xml --log-junit reports/phpunit/unit-test-junit.xml --colors=always
-                    else
-                      bin/phpunit --testsuite unit --colors=always
-                    fi
+            - name: Enable code coverage
+              if: matrix.coverage
+              run: echo "COVERAGE=1" >> $GITHUB_ENV
 
-            -
-                name: Run Integration tests
-                #if: ${{ matrix.php == '7.2' }}
-                run: |
-                    mkdir -p reports/phpunit
-                    if [ "$COVERAGE" = '1' ]; then
-                      bin/phpunit --testsuite integration --coverage-clover reports/phpunit/integration-test-clover.xml --log-junit reports/phpunit/integration-test-junit.xml --colors=always
-                    else
-                      bin/phpunit --testsuite integration --colors=always
-                    fi
-                env:
-                    DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
+            - name: Install PHPUnit
+              run: bin/phpunit install
 
-            # -
-            #   name: Run webserver
-            #   if: ${{ matrix.php == '7.2' }}
-            #   run: symfony server:start --port=8080 --dir=public --daemon --no-tls
+            - name: Run Unit tests
+              #if: ${{ matrix.php == '7.2' }}
+              run: |
+                mkdir -p reports/phpunit
+                if [ "$COVERAGE" = '1' ]; then
+                  bin/phpunit --testsuite unit --coverage-clover reports/phpunit/unit-test-clover.xml --log-junit reports/phpunit/unit-test-junit.xml --colors=always
+                else
+                  bin/phpunit --testsuite unit --colors=always
+                fi
 
-            -
-                name: Run Functional tests
-                #if: ${{ matrix.php == '7.3' }}
-                run: |
-                    mkdir -p reports/phpunit
-                    if [ "$COVERAGE" = '1' ]; then
-                      bin/phpunit --testsuite functional --coverage-clover reports/phpunit/functional-test-clover.xml --log-junit reports/phpunit/functional-test-junit.xml --colors=always
-                    else
-                      bin/phpunit --testsuite functional --colors=always
-                    fi
-                env:
-                    DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
+            - name: Run Integration tests
+              #if: ${{ matrix.php == '7.2' }}
+              run: |
+                mkdir -p reports/phpunit
+                if [ "$COVERAGE" = '1' ]; then
+                    bin/phpunit --testsuite integration --coverage-clover reports/phpunit/integration-test-clover.xml --log-junit reports/phpunit/integration-test-junit.xml --colors=always
+                else
+                    bin/phpunit --testsuite integration --colors=always
+                fi
+              env:
+                DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
+
+#            - name: Run webserver
+#              if: ${{ matrix.php == '7.2' }}
+#              run: symfony server:start --port=8080 --dir=public --daemon --no-tls
+
+
+            - name: Run Functional tests
+              #if: ${{ matrix.php == '7.3' }}
+              run: |
+                mkdir -p reports/phpunit
+                if [ "$COVERAGE" = '1' ]; then
+                    bin/phpunit --testsuite functional --coverage-clover reports/phpunit/functional-test-clover.xml --log-junit reports/phpunit/functional-test-junit.xml --colors=always
+                else
+                    bin/phpunit --testsuite functional --colors=always
+                fi
+              env:
+                DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
 
 
     ci-notify:
@@ -292,13 +265,12 @@ jobs:
         needs: [phpunit]
         runs-on: ubuntu-latest
         steps:
-            -
-                name: Trigger Publish metrics workflow
-                if: success()
-                uses: peter-evans/repository-dispatch@v1
-                with:
-                    token: ${{ secrets.GITHUB_TOKEN }}
-                    repository: ${{ github.repository }}
-                    event-type: pub-metrics
-                    client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
+            - name: Trigger Publish metrics workflow
+              if: success()
+              uses: peter-evans/repository-dispatch@v1
+              with:
+                token: ${{ secrets.GITHUB_TOKEN }}
+                repository: ${{ github.repository }}
+                event-type: pub-metrics
+                client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
 
